(function ensightenInit(){var ensightenOptions = {client: "dell", clientId: 123, publishPath: "marketing", isPublic:0, serverComponentLocation: "nexus.ensighten.com/dell/marketing/serverComponent.php", staticJavascriptPath: "nexus.ensighten.com/dell/marketing/code/", ns: 'Marketing', nexus:"nexus.ensighten.com", scUseCacheBuster: "true", enableTagAuditBeacon : "false", enablePagePerfBeacon : "false", registryNs : "ensBootstraps", generatedOn : "Thu Apr 15 11:40:09 GMT 2021", beaconSamplingSeedValue: 11};
if ( !window[ensightenOptions.ns] ) {
window[ensightenOptions.registryNs]||(window[ensightenOptions.registryNs]={});
window[ensightenOptions.registryNs][ensightenOptions.ns]=window[ensightenOptions.ns]=function(f){function l(a){this.name="DependencyNotAvailableException";this.message="Dependency with id "+a+"is missing"}function m(a){this.name="BeaconException";this.message="There was an error durring beacon initialization";a=a||{};this.lineNumber=a.lineNumber||a.line;this.fileName=a.fileName}function n(){for(var a=b.dataDefinitionIds.length,c=!0,d=0;d<a;d++){var e=b.dataDefinitions[b.dataDefinitionIds[d]];if(!e||
null==e.endRegistration){c=!1;break}}c&&b.callOnDataDefintionComplete()}var e={},b={};b.ensightenOptions=ensightenOptions;b.scDataObj={};e.version="1.26.0";e.nexus=f.nexus||"nexus.ensighten.com";e.rand=-1;e.currSec=(new Date).getSeconds();e.options={interval:f.interval||100,erLoc:f.errorLocation||e.nexus+"/error/e.gif",scLoc:f.serverComponentLocation||e.nexus+"/"+f.client+"/serverComponent.php",sjPath:f.staticJavascriptPath||e.nexus+"/"+f.client+"/code/",alLoc:f.alertLocation||e.nexus+"/alerts/a.gif",
publishPath:f.publishPath,isPublic:f.isPublic,client:f.client,clientId:f.clientId,enableTagAuditBeacon:f.enableTagAuditBeacon,scUseCacheBuster:f.scUseCacheBuster,beaconSamplingSeedValue:f.beaconSamplingSeedValue||-1};e.ruleList=[];e.allDeploymentIds=[];e.runDeploymentIds=[];e.runRuleIds=[];e.exceptionList=[];e.ensightenVariables={};e.test=function(a){if(!(a.executionData.hasRun||a.executionData.runTime&&0<a.executionData.runTime.length)){for(var c=0;c<a.dependencies.length;c++)if(!1===a.dependencies[c]())return;
a.execute()}};l.prototype=Error();l.prototype||(l.prototype={});l.prototype.constructor=l;e.DependencyNotAvailableException=l;m.prototype=Error();m.prototype||(m.prototype={});m.prototype.constructor=m;e.BeaconException=m;e.checkForInvalidDependencies=function(a,c,d,h){for(a=0;a<d.length;a++)if("DEPENDENCYNEVERAVAILABLE"===d[a])return b.currentRuleId=this.id,b.currentDeploymentId=this.deploymentId,b.reportException(new e.DependencyNotAvailableException(h[a])),c&&-1!==c&&e.allDeploymentIds.push(c),
!0;return!1};b.currentRuleId=-1;b.currentDeploymentId=-1;b.reportedErrors=[];b.reportedAlerts=[];b.AF=[];b._serverTime="";b._clientIP="";b.sampleBeacon=function(){var a=!1;try{var c=(e.currSec||0)%20,b=e.options.beaconSamplingSeedValue;-1===b?a=!0:0!==c&&0===b%c&&(a=!0)}catch(h){}return a};b.getServerComponent=function(a){b.callOnGetServerComponent();b.insertScript(window.location.protocol+"//"+e.options.scLoc,!1,a||!0,e.options.scUseCacheBuster)};b.setVariable=function(a,c){e.ensightenVariables[a]=
c};b.getVariable=function(a){return a in e.ensightenVariables?e.ensightenVariables[a]:null};b.testAll=function(){for(var a=0;a<e.ruleList.length;a++)e.test(e.ruleList[a])};b.executionState={DOMParsed:!1,DOMLoaded:!1,dataDefinitionComplete:!1,conditionalRules:!1,readyForServerComponent:!1};b.reportException=function(a){a.timestamp=(new Date).getTime();e.exceptionList.push(a);a=window.location.protocol+"//"+e.options.erLoc+"?msg="+encodeURIComponent(a.message||"")+"&lnn="+encodeURIComponent(a.lineNumber||
a.line||-1)+"&fn="+encodeURIComponent(a.fileName||"")+"&cid="+encodeURIComponent(e.options.clientId||-1)+"&client="+encodeURIComponent(e.options.client||"")+"&publishPath="+encodeURIComponent(e.options.publishPath||"")+"&rid="+encodeURIComponent(b.currentRuleId||-1)+"&did="+encodeURIComponent(b.currentDeploymentId||-1)+"&errorName="+encodeURIComponent(a.name||"");a=b.imageRequest(a);a.timestamp=(new Date).getTime();this.reportedErrors.push(a)};b.Rule=function(a){this.execute=function(){this.executionData.runTime.push(new Date);
b.currentRuleId=this.id;b.currentDeploymentId=this.deploymentId;try{this.code()}catch(c){window[ensightenOptions.ns].reportException(c)}finally{this.executionData.hasRun=!0,-1!==this.deploymentId&&(e.runDeploymentIds.push(this.deploymentId),e.runRuleIds.push(this.id)),b.testAll()}};this.id=a.id;this.deploymentId=a.deploymentId;this.dependencies=a.dependencies||[];this.code=a.code;this.executionData={hasRun:!1,runTime:[]}};b.registerRule=function(a){if(b.getRule(a.id)&&-1!==a.id)return!1;e.ruleList.push(a);
-1!==a.deploymentId&&e.allDeploymentIds.push(a.deploymentId);b.testAll();return!0};b.getRule=function(a){for(var c=0;c<e.ruleList.length;c++)if(e.ruleList[c].id===a)return e.ruleList[c];return!1};b.getRuleList=function(){return e.ruleList};b.clearRuleList=function(){e.ruleList=[]};b.getAllDeploymentIds=function(){return e.allDeploymentIds};b.getRunRuleIds=function(){return e.runRuleIds};b.getRunDeploymentIds=function(){return e.runDeploymentIds};b.hasRuleRun=function(a){return(a=b.getRule(a))?a.executionData.hasRun:
!1};e.toTwoChar=function(a){return(2===a.toString().length?"":"0")+a};b.Alert=function(a){var c=new Date;c=c.getFullYear()+"-"+e.toTwoChar(c.getMonth())+"-"+e.toTwoChar(c.getDate())+" "+e.toTwoChar(c.getHours())+":"+e.toTwoChar(c.getMinutes())+":"+e.toTwoChar(c.getSeconds());this.severity=a.severity||1;this.subject=a.subject||"";this.type=a.type||1;this.ruleId=a.ruleId||-1;this.severity=encodeURIComponent(this.severity);this.date=encodeURIComponent(c);this.subject=encodeURIComponent(this.subject);
this.type=encodeURIComponent(this.type)};b.generateAlert=function(a){a=b.imageRequest(window.location.protocol+"//"+e.options.alLoc+"?d="+a.date+"&su="+a.subject+"&se="+a.severity+"&t="+a.type+"&cid="+e.options.clientId+"&client="+e.options.client+"&publishPath="+e.options.publishPath+"&rid="+b.currentRuleId+"&did="+b.currentDeploymentId);a.timestamp=(new Date).getTime();this.reportedAlerts.push(a)};b.imageRequest=function(a){var c=new Image(0,0);c.src=a;return c};b.insertScript=function(a,c,d,h){var p=
document.getElementsByTagName("script"),g;h=void 0!==h?h:!0;if(void 0!==c?c:1)for(g=0;g<p.length;g++)if(p[g].src===a&&p[g].readyState&&/loaded|complete/.test(p[g].readyState))return;if(d){d=1==d&&"object"==typeof b.scDataObj?b.scDataObj:d;e.rand=Math.random()*("1E"+(10*Math.random()).toFixed(0));c=window.location.href;"object"===typeof d&&d.PageID&&(c=d.PageID,delete d.PageID);if("object"===typeof d)for(g in d){g=~c.indexOf("#")?c.slice(c.indexOf("#"),c.length):"";c=c.slice(0,g.length?c.length-g.length:
c.length);c+=~c.indexOf("?")?"&":"?";for(k in d)c+=k+"="+d[k]+"&";c=c.slice(0,-1)+g;break}a+="?";h&&(a+="r="+e.rand+"&");a+="namespace="+ensightenOptions.ns+"&";a+="staticJsPath="+ensightenOptions.staticJavascriptPath+"&";a+="publishedOn="+ensightenOptions.generatedOn+"&";a+="ClientID="+encodeURIComponent(e.options.clientId)+"&PageID="+encodeURIComponent(c)}(function(a,c,b){var d=c.head||c.getElementsByTagName("head");setTimeout(function(){if("item"in d){if(!d[0]){setTimeout(arguments.callee,25);
return}d=d[0]}var a=c.createElement("script");a.src=b;a.onload=a.onerror=function(){this.addEventListener&&(this.readyState="loaded")};d.insertBefore(a,d.firstChild)},0)})(window,document,a)};b.loadScriptCallback=function(a,c,b){var d=document.getElementsByTagName("script"),e;b=d[0];for(e=0;e<d.length;e++)if(d[e].src===a&&d[e].readyState&&/loaded|complete/.test(d[e].readyState))try{c()}catch(g){window[ensightenOptions.ns].reportException(g)}finally{return}d=document.createElement("script");d.type=
"text/javascript";d.async=!0;d.src=a;d.onerror=function(){this.addEventListener&&(this.readyState="loaded")};d.onload=d.onreadystatechange=function(){if(!this.readyState||"complete"===this.readyState||"loaded"===this.readyState){this.onload=this.onreadystatechange=null;this.addEventListener&&(this.readyState="loaded");try{c.call(this)}catch(g){window[ensightenOptions.ns].reportException(g)}}};b.parentNode.insertBefore(d,b)};b.insertPageFiles=function(a){var b=0,d=0,e=function(){d==a.length-1&&window[ensightenOptions.ns].callOnPageSpecificCompletion();
d++};for(b=0;b<a.length;++b)window[ensightenOptions.ns].loadScriptCallback(a[b],e)};b.unobtrusiveAddEvent=function(a,b,d){try{var c=a[b]?a[b]:function(){};a[b]=function(){d.apply(this,arguments);return c.apply(this,arguments)}}catch(p){window[ensightenOptions.ns].reportException(p)}};b.anonymous=function(a,c){return function(){try{b.currentRuleId=c?c:"anonymous",a()}catch(d){window[ensightenOptions.ns].reportException(d)}}};b.setCurrentRuleId=function(a){b.currentRuleId=a};b.setCurrentDeploymentId=
function(a){b.currentDeploymentId=a};b.bindImmediate=function(a,c,d){if("function"===typeof a)a=new b.Rule({id:c||-1,deploymentId:d||-1,dependencies:[],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindDOMParsed=function(a,c,d){if("function"===typeof a)a=new b.Rule({id:c||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.DOMParsed}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindDOMLoaded=function(a,c,d){if("function"===
typeof a)a=new b.Rule({id:c||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.DOMLoaded}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindPageSpecificCompletion=function(a,c,d){if("function"===typeof a)a=new b.Rule({id:c||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.conditionalRules}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindOnGetServerComponent=
function(a,c,d){if("function"===typeof a)a=new b.Rule({id:c||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.readyForServerComponent}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindDataDefinitionComplete=function(a,c,d){if("function"===typeof a)a=new b.Rule({id:c||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.dataDefinitionComplete}],code:a});else if("object"!==typeof a)return!1;
b.registerRule(a)};b.checkHasRun=function(a){if(0===a.length)return!0;for(var c,d=0;d<a.length;++d)if(c=b.getRule(parseInt(a[d],10)),!c||!c.executionData.hasRun)return!1;return!0};b.bindDependencyImmediate=function(a,c,d,h,f){var g=[];if(!e.checkForInvalidDependencies(c,h,d,f)){g.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:c||-1,deploymentId:h||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyDOMLoaded=
function(a,c,d,h,f){var g=[];if(!e.checkForInvalidDependencies(c,h,d,f)){g.push(function(){return window[ensightenOptions.ns].executionState.DOMLoaded});g.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:c||-1,deploymentId:h||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyDOMParsed=function(a,c,d,h,f){var g=[];if(!e.checkForInvalidDependencies(c,h,d,f)){g.push(function(){return window[ensightenOptions.ns].executionState.DOMParsed});
g.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:c||-1,deploymentId:h||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyPageSpecificCompletion=function(a,c,d,h,f){var g=[];if(!e.checkForInvalidDependencies(c,h,d,f)){g.push(function(){return window[ensightenOptions.ns].executionState.conditionalRules});g.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===
typeof a)a=new b.Rule({id:c||-1,deploymentId:h||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyOnGetServerComponent=function(a,c,d,h,f){var g=[];if(!e.checkForInvalidDependencies(c,h,d,f)){g.push(function(){return window[ensightenOptions.ns].executionState.readyForServerComponent});g.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:c||-1,deploymentId:h||-1,dependencies:g,code:a});else if("object"!==
typeof a)return!1;b.registerRule(a)}};b.bindDependencyPageSpecificCompletion=function(a,c,d,f,p){var g=[];if(!e.checkForInvalidDependencies(c,f,d,p)){g.push(function(){return window[ensightenOptions.ns].executionState.dataDefinitionComplete});g.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:c||-1,deploymentId:f||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.dataDefintionIds=[];b.dataDefinitions=
[];b.pageSpecificDataDefinitionsSet=!1;b.setPageSpecificDataDefinitionIds=function(a){for(var c=a?a.length:0,d=0;d<c;d++){var e=a[d];if(Array.prototype.indexOf)-1==b.dataDefinitionIds.indexOf(e)&&b.dataDefinitionIds.push(e);else{for(var f=!1,g=b.dataDefinitionIds.length,l=0;l<g;l++)if(b.dataDefinitionIds[l]===e){f=!0;break}f||b.dataDefinitionIds.push(e)}}b.pageSpecificDataDefinitionsSet=!0;n()};b.DataDefinition=function(a,b){this.id=a;this.registrationFn=b;this.endRegistrationTime=this.startRegistrationTime=
null;this.startRegistration=function(){this.startRegistrationTime=new Date};this.endRegistration=function(){this.endRegistrationTime=new Date}};b.registerDataDefinition=function(a,c){var d=b.dataDefinitions[c];d||(d=new b.DataDefinition(c,a),b.dataDefinitions[c]=d);d.startRegistrationTime||(d.startRegistration(),d.registrationFn(),d.endRegistration());b.pageSpecificDataDefinitionsSet&&n()};b.callOnDataDefintionComplete=function(){b.executionState.dataDefinitionComplete=!0;b.testAll()};b.callOnDOMParsed=
function(){window[ensightenOptions.ns].executionState.DOMParsed=!0;window[ensightenOptions.ns].testAll()};b.callOnDOMLoaded=function(){window[ensightenOptions.ns].executionState.DOMParsed=!0;window[ensightenOptions.ns].executionState.DOMLoaded=!0;window[ensightenOptions.ns].testAll()};b.callOnPageSpecificCompletion=function(){for(var a=document.getElementsByTagName("script"),b=0,d=a.length;b<d;b++)if(a[b].src&&a[b].src.match(/\.ensighten\.com\/(.+?)\/code\/.*/i)&&"loaded"!=a[b].readyState&&"complete"!=
a[b].readyState){setTimeout(window[ensightenOptions.ns].callOnPageSpecificCompletion,50);return}setTimeout(function(){window[ensightenOptions.ns].executionState.conditionalRules=!0;window[ensightenOptions.ns].testAll()},1)};b.callOnGetServerComponent=function(){window[ensightenOptions.ns].executionState.readyForServerComponent=!0;window[ensightenOptions.ns].testAll()};b.hasDOMParsed=function(){return window[ensightenOptions.ns].executionState.DOMParsed};b.hasDOMLoaded=function(){return window[ensightenOptions.ns].executionState.DOMLoaded};
b.hasPageSpecificCompletion=function(){return window[ensightenOptions.ns].executionState.conditionalRules};var r=function(){var a=[],b=!1,d=!1;return{add:function(c){b&&!d?c():"function"==typeof c&&(a[a.length]=c)},exec:function(){d=!0;do{var c=a;a=[];b=!0;for(var e=0;e<c.length;e++)try{c[e].call(window)}catch(g){window[ensightenOptions.ns].reportException(g)}}while(0<a.length);d=!1},haveRun:function(){return b}}};b.new_fArray=function(){return r()};e.timer=null;(function(){function a(a,b){return function(){a.apply(b,
arguments)}}window.console||(window.console={});var b=window.console;if(!b.log)if(window.log4javascript){var d=log4javascript.getDefaultLogger();b.log=a(d.info,d);b.debug=a(d.debug,d);b.info=a(d.info,d);b.warn=a(d.warn,d);b.error=a(d.error,d)}else b.log=function(){};b.debug||(b.debug=b.log);b.info||(b.info=b.log);b.warn||(b.warn=b.log);b.error||(b.error=b.log)})();document.addEventListener?(-1<navigator.userAgent.indexOf("AppleWebKit/")?e.timer=window.setInterval(function(){/loaded|interactive|complete/.test(document.readyState)&&
(clearInterval(e.timer),b.callOnDOMParsed())},50):document.addEventListener("DOMContentLoaded",b.callOnDOMParsed,!1),window.addEventListener("load",b.callOnDOMLoaded,!1)):(setTimeout(function(){var a=window.document;(function(){try{if(!document.body)throw"continue";a.documentElement.doScroll("left")}catch(c){setTimeout(arguments.callee,15);return}window[ensightenOptions.ns].callOnDOMParsed()})()},1),window.attachEvent("onload",function(){window[ensightenOptions.ns].callOnDOMLoaded()}));document.readyState&&
"complete"===document.readyState&&(b.executionState.DOMParsed=!0,b.executionState.DOMLoaded=!0);"true"===e.options.enableTagAuditBeacon&&b.sampleBeacon()&&window.setTimeout(function(){if(window[ensightenOptions.ns]&&!window[ensightenOptions.ns].mobilePlatform)try{for(var a=[],c,d,h,l,g=0;g<e.ruleList.length;++g)d=e.ruleList[g],h=d.executionData.hasRun?"1":"0",l=d.deploymentId.toString()+"|"+d.id.toString()+"|"+h,a.push(l);c="["+a.join(";")+"]";var m=window.location.protocol+"//"+e.nexus+"/"+encodeURIComponent(f.client)+
"/"+encodeURIComponent(f.publishPath)+"/TagAuditBeacon.rnc?cid="+encodeURIComponent(f.clientId)+"&data="+c+"&idx=0&r="+e.rand;b.imageRequest(m)}catch(q){b.currentRuleId=-1,b.currentDeploymentId=-1,a=new e.BeaconException(q),window[ensightenOptions.ns].reportException(a)}},3E3);window.setInterval(b.testAll,e.options.interval);return b}(ensightenOptions);
"true"===ensightenOptions.enablePagePerfBeacon&&window[ensightenOptions.ns]&&window[ensightenOptions.ns].sampleBeacon()&&window[ensightenOptions.ns].bindDOMParsed(function(){if(!window[ensightenOptions.ns].mobilePlatform){var f=window.performance;if(f){f=f.timing||{};var l=f.navigationStart||0,m={connectEnd:"ce",connectStart:"cs",domComplete:"dc",domContentLoadedEventEnd:"dclee",domContentLoadedEventStart:"dcles",domInteractive:"di",domLoading:"dl",domainLookupEnd:"dle",domainLookupStart:"dls",fetchStart:"fs",
loadEventEnd:"lee",loadEventStart:"les",redirectEnd:"rede",redirectStart:"reds",requestStart:"reqs",responseStart:"resps",responseEnd:"respe",secureConnectionStart:"scs",unloadEventStart:"ues",unloadEventEnd:"uee"};var n="&ns="+encodeURIComponent(f.navigationStart);for(var e in m)if(void 0!==f[e]){var b=f[e]-l;n+="&"+m[e]+"="+(0<b?encodeURIComponent(b):0)}else n+="&"+m[e]+"=-1";window[ensightenOptions.ns].timing=n;e=ensightenOptions.nexus||"nexus.ensighten.com";f=ensightenOptions.staticJavascriptPath||
"";n=f.indexOf("/",0);l=f.indexOf("/code/");f=f.substring(n,l)+"/perf.rnc";f+="?cid="+encodeURIComponent(ensightenOptions.clientId)+window[ensightenOptions.ns].timing;window[ensightenOptions.ns].imageRequest("//"+e+f)}}});
		Marketing.dataDefinitionIds = [];Marketing.bindDependencyImmediate(function(){var Bootstrapper=window["Marketing"];var ensightenOptions=Marketing.ensightenOptions;try{var eu_list={at:"AT",be:"BE",bg:"BG",hr:"HR",cy:"CY",cz:"CZ",dk:"DK",ee:"EE",fi:"FI",fr:"FR",de:"DE",gr:"GR",hu:"HU",ie:"IE",it:"IT",lv:"LV",lt:"LT",lu:"LU",mt:"MT",nl:"NL",pl:"PL",pt:"PT",ro:"RO",sk:"SK",si:"SI",es:"ES",se:"SE",gb:"GB",uk:"UK"};Marketing.UDO.priorconsent=!eu_list[Marketing.scDataObj.country]||(dell_marketing_util.getCookie("_evidon_consent_cookie")?
true:false);window.evidon.priorConsentCallback=function(){Marketing.scDataObj.consent=true;Marketing.UDO.priorconsent=true;var event,eventName="privacy-consent-true";if(document.createEvent){event=document.createEvent("Event");event.initEvent(eventName,true,true);event.eventName=eventName;window.dispatchEvent(event)}}}catch(e){dell_marketing_util.debug(e)}},3207360,[3496429],632580,[610323]);
Marketing.bindImmediate(function(){var Bootstrapper=window["Marketing"];var ensightenOptions=Marketing.ensightenOptions;(function(){function s(e,t,n){var r=t=="blur"||t=="focus";e.element.addEventListener(t,n,r)}function o(e){e.preventDefault();e.stopPropagation()}function u(t){if(e)return e;if(t.matches)e=t.matches;if(t.webkitMatchesSelector)e=t.webkitMatchesSelector;if(t.mozMatchesSelector)e=t.mozMatchesSelector;if(t.msMatchesSelector)e=t.msMatchesSelector;if(t.oMatchesSelector)e=t.oMatchesSelector;
if(!e)e=p.matchesSelector;return e}function a(element,n,r){if(n=="_root")return r;if(element===r)return;try{if(u(element).call(element,n))return element}catch(error){e=null;if(u(element).call(element,n))return element}if(element.parentNode){t++;return a(element.parentNode,n,r)}}function f(e,t,n,i){if(!r[e.id])r[e.id]={};if(!r[e.id][t])r[e.id][t]={};if(!r[e.id][t][n])r[e.id][t][n]=[];r[e.id][t][n].push(i)}function l(e,t,n,i){if(!i&&!n){r[e.id][t]={};return}if(!i){delete r[e.id][t][n];return}for(var s=
0;s<r[e.id][t][n].length;s++)if(r[e.id][t][n][s]===i){r[e.id][t][n].pop(s,1);break}}function c(e,n,s){if(!r[e][s])return;var o=n.target||n.srcElement,u,f,l={},c=0,h=0;t=0;for(u in r[e][s])if(r[e][s].hasOwnProperty(u)){f=a(o,u,i[e].element);if(f&&p.matchesEvent(s,i[e].element,f,u=="_root",n)){t++;r[e][s][u].match=f;l[t]=r[e][s][u]}}n.stopPropagation=function(){n.cancelBubble=true};for(c=0;c<=t;c++)if(l[c])for(h=0;h<l[c].length;h++){if(l[c][h].call(l[c].match,n)===false){p.cancel(n);return}if(n.cancelBubble)return}}
function h(e,t,n,i){function u(e){return function(t){c(s,t,e)}}if(!(e instanceof Array))e=[e];if(!n&&typeof t=="function"){n=t;t="_root"}var s=this.id,o;for(o=0;o<e.length;o++){if(!r[s]||!r[s][e[o]])p.addEvent(this,e[o],u(e[o]));if(i){l(this,e[o],t,n);continue}f(this,e[o],t,n)}return this}function p(e,t){if(typeof e=="string"&&typeof t=="function"||typeof t=="string")p(document).on(arguments[0],arguments[1],arguments[2],arguments[3]||false);if(!(this instanceof p)){for(var r in i)if(i[r].element===
e)return i[r];n++;i[n]=new p(e,n);i[n]._on=i[n].on;i[n].on=function(e,t,n,r){var i=typeof t=="function"?t:n,s=typeof t=="function"?n||false:r||false;if(!s)return this._on.call(this,e,t,n);else{var o=[e];if(typeof t=="string")o.push(t);o.push(function(e){return function(t){if(!t.defaultPrevented)Bootstrapper.Delegate.load(this,s);if(typeof t.preventDefault!="undefined")t.preventDefault();else t.returnValue=false;e.call(this)}}(i));this._on.apply(this,o)}};return i[n]}this.element=e;this.id=t}var e,
t=0,n=0,r={},i={};_delay=750;p.prototype.on=function(e,t,n){return h.call(this,e,t,n)};p.prototype.off=function(e,t,n){return h.call(this,e,t,n,true)};p.matchesSelector=function(){};p.cancel=o;p.addEvent=s;p.matchesEvent=function(){return true};p.load=function(e,t){var n=typeof t=="number"?parseInt(t):750;setTimeout(function(e,t){return function(){if(e.nodeName&&"a"==e.nodeName.toLowerCase()){if(t&&/^javascript\s*:/.test(t))return(new Function(unescape(t))).call(window);else if(e.target&&/_blank|_new/i.test(e.target))return true;
if(t)window.location.href=t}}}(e,e.href||""),n)};Bootstrapper.Delegate=p})();(function(e){var t=e.addEvent;e.addEvent=function(e,n,r){if(e.element.addEventListener)return t(e,n,r);if(n=="focus")n="focusin";if(n=="blur")n="focusout";e.element.attachEvent("on"+n,r)};e.simpleMatchesSelector=function(e){if(e.charAt(0)===".")return(" "+this.className+" ").indexOf(" "+e.slice(1)+" ")>-1;if(e.charAt(0)==="#")return this.id===e.slice(1);return this.tagName.toUpperCase()===e.toUpperCase()};e.matchesSelector=
function(t){if(!~t.indexOf(" ")&&!~t.indexOf("\x3e"))return e.simpleMatchesSelector.call(this,t);else{var n=this,r=t.split(" ").reverse();while(r.length){var i=r.shift();if(~i.indexOf("\x3e")){i=i.split("\x3e").reverse();while(i.length){tempSel=i.shift();if(e.simpleMatchesSelector.call(n,tempSel))n=n.parentNode;else return false}if(!r.length)return true}else while(n!=document){var s=e.simpleMatchesSelector.call(n,i);if(n.parentNode)n=n.parentNode;n=n.parentnode?n.parentnode:document;if(s){if(!r.length)return true;
break}}}return false}};e.cancel=function(e){if(e.preventDefault)e.preventDefault();if(e.stopPropagation)e.stopPropagation();e.returnValue=false;e.cancelBubble=true}})(Bootstrapper.Delegate);Bootstrapper.on=Bootstrapper.Delegate;Bootstrapper.getQueryParam=function(key,loc){if(!this.params||loc){var search=loc||window.location.search;var params=search.replace(/^\?/,""),paramObj={};params=params.split("\x26");for(var i=0;i<params.length;i++){var t=params[i].split("\x3d");paramObj[t[0]]=t[1]}if(!loc)this.params=
paramObj;else return paramObj[key]||""}return this.params[key]||""};window.dell_marketing_util={};Dell=window.Dell||{};Dell.Metrics=Dell.Metrics||{};Dell.Metrics.sc=Dell.Metrics.sc||{};dell_marketing_util.getCookie=function(cookie_name){var results=document.cookie.match("(^|;) ?"+cookie_name+"\x3d([^;]*)(;|$)");if(results)return unescape(results[2]);else return null};dell_marketing_util.setCookie=function(name,val,opts){var cookie;cookie=name+"\x3d"+val;if(opts){if(opts.expDate)cookie+="; expires\x3d"+
opts.expDate.toGMTString();if(opts.path)cookie+="; path\x3d"+escape(opts.path);if(opts.domain)cookie+="; domain\x3d"+escape(opts.domain);if(opts.secure)cookie+="; secure"}return document.cookie=cookie};dell_marketing_util.getParameterByName=function(name,qstring){name=name.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");var regex=new RegExp("[\\?\x26]"+name+"\x3d([^\x26#]*)"),results=regex.exec(qstring);return results===null?"":decodeURIComponent(results[1].replace(/\+/g," "))};dell_marketing_util.iFrame=
function(){try{return window.self!==window.top}catch(e){return true}};dell_marketing_util.debug=function(errorMessage){if(Marketing.ensightenOptions.publishPath==="marketingdev"||dell_marketing_util.getParameterByName("mdebug",location.search)==="true"||dell_marketing_util.getCookie("mdebug")==="true")console.error(errorMessage)};dell_marketing_util.getscMap=function(key){var scMap=Dell.Metrics.sc;return typeof scMap[key]!="undefined"?typeof scMap[key]==="string"?scMap[key].toLowerCase():scMap[key]:
"undefined"};if(dell_marketing_util.getscMap("country")!=="undefined"&&dell_marketing_util.getscMap("language")!=="undefined"&&dell_marketing_util.getscMap("segment")!=="undefined"&&dell_marketing_util.getscMap("customerset")!=="undefined"&&dell_marketing_util.getscMap("cms")!=="undefined"){Marketing.scDataObj.country=dell_marketing_util.getscMap("country");Marketing.scDataObj.language=dell_marketing_util.getscMap("language");Marketing.scDataObj.segment=dell_marketing_util.getscMap("segment");Marketing.scDataObj.cset=
dell_marketing_util.getscMap("customerset");Marketing.scDataObj.categoryid=dell_marketing_util.getscMap("categoryid");Marketing.scDataObj.cms=dell_marketing_util.getscMap("cms");Marketing.scDataObj.page=dell_marketing_util.getscMap("wacontroller");Marketing.scDataObj.module=dell_marketing_util.getscMap("module")}else{var metaTags=document.getElementsByTagName("meta"),metaName="",metaContent="",metaCount=0,metaLength=metaTags.length;Marketing.scDataObj=Marketing.scDataObj||{};for(metaCount;metaCount<
metaLength;metaCount++){metaName=metaTags[metaCount].name||"";metaContent=metaTags[metaCount].content.toLowerCase()||"";if(/language/i.test(metaName))Marketing.scDataObj.language=Dell.Metrics.sc.language=metaContent;else if(/segment/i.test(metaName))Marketing.scDataObj.segment=Dell.Metrics.sc.segment=metaContent;else if(/customerset/i.test(metaName))Marketing.scDataObj.cset=Dell.Metrics.sc.customerset=metaContent;else if(/documentcountrycode|country/i.test(metaName))Marketing.scDataObj.country=Dell.Metrics.sc.country=
metaContent;else if(/generator/i.test(metaName)){var cmsVal="other";if(/^storm/i.test(metaContent))cmsVal="Storm";else if(/^ng/i.test(metaContent))cmsVal="NG";else if(/^(stp|transactional)/i.test(metaContent))cmsVal="STP";else if(/^mse/i.test(metaContent))cmsVal="FUELSPA";else if(/^build:\s\d+\./i.test(metaContent))cmsVal=metaContent.split("Built")[0].replace(/(\s|:)/g,"");Marketing.scDataObj.cms=Dell.Metrics.sc.cms=cmsVal}}var location_href=window.location.href,lwp=dell_marketing_util.getCookie("lwp");
if(typeof Marketing.scDataObj.cset==="undefined")if(/cs=/i.test(location_href))Marketing.scDataObj.cset=Dell.Metrics.sc.customerset=dell_marketing_util.getParameterByName("cs",location_href);else Marketing.scDataObj.cset=Dell.Metrics.sc.customerset=dell_marketing_util.getParameterByName("cs",lwp);if(typeof Marketing.scDataObj.segment==="undefined")if(/\\?s=/i.test(location_href)||/&s=/i.test(location_href))Marketing.scDataObj.segment=Dell.Metrics.sc.segment=dell_marketing_util.getParameterByName("s",
location_href);else Marketing.scDataObj.segment=Dell.Metrics.sc.segment=dell_marketing_util.getParameterByName("s",lwp);metaTags=null}},3310052,610310);
Marketing.bindDependencyImmediate(function(){var Bootstrapper=window["Marketing"];var ensightenOptions=Marketing.ensightenOptions;try{Marketing=Marketing||{};Marketing.UDO=Marketing.UDO||{};MasterTmsUdo=window.MasterTmsUdo||{};MasterTmsUdo.CJ=MasterTmsUdo.CJ||{};var searchStr=location.href;searchStr=searchStr.replace(/ven(\d)=/ig,"ven$1\x3d");var ven1=dell_marketing_util.getParameterByName("ven1",searchStr);searchStr=searchStr.replace(/gacd=/ig,"gacd\x3d");var gacd=dell_marketing_util.getParameterByName("gacd",
searchStr);searchStr=searchStr.replace(/clickid=/ig,"clickid\x3d");var clickid=dell_marketing_util.getParameterByName("clickid",searchStr);searchStr=searchStr.replace(/utm_source=Rakuten/ig,"rkt\x3dtrue");var rkt=dell_marketing_util.getParameterByName("rkt",searchStr);if(!dell_marketing_util.iFrame())if(sessionStorage.enspagecountFLT)sessionStorage.enspagecountFLT=Number(sessionStorage.enspagecountFLT)+1;else sessionStorage.enspagecountFLT=1;var setAdCookies=function(){var exp,land,days;exp=new Date;
land=new Date;days=90;exp.setTime(exp.getTime()+days*24*60*60*1E3);if(ven1){dell_marketing_util.setCookie("dellven",ven1,{domain:"dell.com",path:"/",expDate:exp});dell_marketing_util.setCookie("dellland",land.getTime(),{domain:"dell.com",path:"/",expDate:exp})}if(gacd)dell_marketing_util.setCookie("dellgacd",gacd,{domain:"dell.com",path:"/",expDate:exp});if(clickid)dell_marketing_util.setCookie("dellclickid",clickid,{domain:"dell.com",path:"/",expDate:exp});if(rkt)dell_marketing_util.setCookie("RKT",
rkt,{domain:"dell.com",path:"/",expDate:exp})};setAdCookies();var dellvenCookieVal=dell_marketing_util.getCookie("dellven")||"";dell_marketing_util.getUdoMap=function(key){var udoMap=MasterTmsUdo.CJ;return typeof udoMap[key]!="undefined"&&typeof udoMap[key]=="string"?udoMap[key].toLowerCase():udoMap[key]||""};dell_marketing_util.custom_marketing_event=function(eventName){var event;if(document.createEvent){event=document.createEvent("Event");event.initEvent(eventName,true,true);event.eventName=eventName;
window.dispatchEvent(event)}};dell_marketing_util.createIframe=function(name,src){src=src||"javascript:void(0)";var ifrm=document.createElement("iframe");ifrm.setAttribute("src",src);ifrm.setAttribute("name",name);ifrm.style.visibility="hidden";ifrm.style.position="absolute";ifrm.style.bottom="0";ifrm.width="0";ifrm.height="0";ifrm.frameBorder="0";document.body.appendChild(ifrm)};dell_marketing_util.createElement=function(srcUrl,elem){var elemTag=document.createElement(elem);elemTag.src=srcUrl;elemTag.async=
true;elemTag.height="0";elemTag.width="0";elemTag.style.visibility="hidden";elemTag.style.position="absolute";elemTag.style.bottom="0";elemTag.frameBorder="0";top.document.body.appendChild(elemTag)};dell_marketing_util.getDpid=function(preserveFormat){var dpid=Dell.Metrics.sc.dpid||MasterTmsUdo.CJ.DPID;if(dpid){if(preserveFormat)return dpid.toString();return dpid.toString().replace(/-/gi,"")}return""};dell_marketing_util.serialProductList=function(){var serialProdList="";if(/9|100/.test(dell_marketing_util.getUdoMap("PROMOID"))){serialProdList=
[];var cartData=Dell.Transactional?Dell.Transactional.Cart.Metrics.Data.Analytics.FlattenedItems:"",prodList=dell_marketing_util.getUdoMap("PRODUCTLIST");for(var i=0;i<prodList.length;i++){var cartDataPrice=cartData?cartData[i].Price:"";serialProdList.push(prodList[i].ITEM+":"+prodList[i].AMT+":"+prodList[i].QTY+":"+cartDataPrice)}return serialProdList.join("|")}return serialProdList};Marketing.UDO.readData=function(){Marketing.UDO.accountid=dell_marketing_util.getUdoMap("ACCOUNTID");Marketing.UDO.category=
dell_marketing_util.getUdoMap("CATEGORY");Marketing.UDO.categorypath=dell_marketing_util.getUdoMap("CATEGORYPATH");Marketing.UDO.cid=dell_marketing_util.getUdoMap("CID");Marketing.UDO.coupon=dell_marketing_util.getUdoMap("COUPON");Marketing.UDO.cseg=dell_marketing_util.getUdoMap("CSEG");Marketing.UDO.currency=dell_marketing_util.getUdoMap("CURRENCY");Marketing.UDO.deals=dell_marketing_util.getUdoMap("DEALS");Marketing.UDO.device=dell_marketing_util.getUdoMap("DEVICE");Marketing.UDO.discount=dell_marketing_util.getUdoMap("DISCOUNT");
Marketing.UDO.emailhash=dell_marketing_util.getUdoMap("EMAILHASH");Marketing.UDO.family=dell_marketing_util.getUdoMap("FAMILY");Marketing.UDO.ogid=dell_marketing_util.getUdoMap("OGID");Marketing.UDO.family=dell_marketing_util.getUdoMap("FAMILY");Marketing.UDO.ordercode=dell_marketing_util.getUdoMap("ORDERCODE");Marketing.UDO.platform=dell_marketing_util.getUdoMap("PLATFORM");Marketing.UDO.prodcat=dell_marketing_util.getUdoMap("PRODCAT");Marketing.UDO.product=dell_marketing_util.getUdoMap("PRODUCT");
Marketing.UDO.productlist=dell_marketing_util.getUdoMap("PRODUCTLIST");Marketing.UDO.promoid=dell_marketing_util.getUdoMap("PROMOID");Marketing.UDO.revenue=dell_marketing_util.getUdoMap("REVENUE");Marketing.UDO.type=dell_marketing_util.getUdoMap("TYPE");Marketing.UDO.country=Marketing.scDataObj.country;Marketing.UDO.language=Marketing.scDataObj.language;Marketing.UDO.segment=Marketing.scDataObj.segment;Marketing.UDO.dpid=dell_marketing_util.getDpid(true);Marketing.UDO.serialprodlist=dell_marketing_util.serialProductList();
if(Marketing.UDO.currency.toLowerCase()==="usd")Marketing.UDO.usdrev=Marketing.UDO.revenue;else Marketing.UDO.usdrev=dell_marketing_util.getUdoMap("CONV_REVENUE");Marketing.UDO.udoReady=Marketing.scDataObj.cms=="olr"?false:true};Marketing.UDO.readData();window.addEventListener("datalayerReady",function(){Marketing.UDO.readData();var ogid=dell_marketing_util.getscMap("ordergroupid");if(ogid!="undefined")Marketing.UDO.ogid=ogid;if(!Marketing.UDO.dpid&&Marketing.UDO.promoid=="100")Marketing.on("click",
".dellmetrics-pp",function(){Marketing.UDO.dpid=dell_marketing_util.getDpid(true);Marketing.UDO.udoReady=true;dell_marketing_util.custom_marketing_event("udoReady")});else{Marketing.UDO.udoReady=true;dell_marketing_util.custom_marketing_event("udoReady")}});window.Pulse=window.Pulse||{runWidget:function(){dell_marketing_util.custom_marketing_event("datalayerReady");return true}};window.addEventListener("hve",function(e){if(e.detail.type==="download"&&window.location.hash.includes("overlay\x3d"))Marketing.UDO.hveoverlay=
true});Marketing.UDO.gacd=dell_marketing_util.getCookie("dellgacd")||"";Marketing.UDO.land=dell_marketing_util.getCookie("dellland")||"";Marketing.UDO.clickid=dell_marketing_util.getCookie("dellclickid")||"";Marketing.UDO.rkt=dell_marketing_util.getCookie("RKT")||"";Marketing.UDO.cjevent=dell_marketing_util.getCookie("cjevent")||"";Marketing.UDO.ven1=dellvenCookieVal.split("|")[0]||"";Marketing.UDO.ven2=dell_marketing_util.getParameterByName("ven2",searchStr);Marketing.UDO.ven3=dell_marketing_util.getParameterByName("ven3",
searchStr);Marketing.UDO.mcmid="";var adobe_mcmid=dell_marketing_util.getCookie("AMCV_4DD80861515CAB990A490D45%40AdobeOrg");if(adobe_mcmid.includes("MCMID|"))Marketing.UDO.mcmid=adobe_mcmid.split("MCMID|")[1].split("|")[0];Marketing.UDO.hve_mpv=function(srcUrl,elem){var elem=elem||"img";if(sessionStorage.enspagecountFLT==3)dell_marketing_util.createElement(srcUrl,elem)};Marketing.UDO.hve_download=function(srcUrl,elem){var elem=elem||"img";window.addEventListener("hve",function(e){Marketing.UDO.hveoverlay=
false;if(e.detail.type==="download")dell_marketing_util.createElement(srcUrl,elem)});if(Marketing.UDO.hveoverlay)dell_marketing_util.createElement(srcUrl,elem)};Marketing.UDO.hve_contactUs=function(srcUrl,elem){var elem=elem||"img";window.addEventListener("hve",function(e){if(e.detail.type==="contactus")dell_marketing_util.createElement(srcUrl,elem)})};Marketing.UDO.hve_chat=function(srcUrl,elem){var elem=elem||"img";window.addEventListener("hve",function(e){if(e.detail.type==="chat")dell_marketing_util.createElement(srcUrl,
elem)})};var video_hist=[];Marketing.UDO.hve_ytube=function(srcUrl,elem){var elem=elem||"img";var parent=window.top;var doc=top.document;parent.addEventListener("hashchange",yt_video);yt_videos=top.document.querySelectorAll('a[href*\x3d"youtube"]');for(i=0;i<yt_videos.length;i++)yt_videos[i].addEventListener("click",yt_video_handler);function yt_video_handler(e){var elemTag=document.createElement(elem);elemTag.src=srcUrl;elemTag.async=true;elemTag.height=1;elemTag.width=1;top.document.body.appendChild(elemTag);
e.currentTarget.removeEventListener("click",yt_video_handler)}function yt_video(){var hash=parent.location.hash;var img=document.createElement("img");var vid=hash.substring(hash.indexOf("video-overlay"),hash.length).split("\x3d")[1];if(video_hist.indexOf(vid)==-1)if(hash.indexOf("video-overlay")==-1)return;else if(hash.indexOf("video-overlay")!==-1){var elemTag=document.createElement(elem);elemTag.src=srcUrl;elemTag.height=1;elemTag.width=1;parent.document.body.appendChild(elemTag);video_hist.push(vid)}}
};Marketing.UDO.hve_bc_start=function(srcUrl,elem){if(typeof videojs!=="undefined"&&videojs.players)for(var v in videojs.players)videojs.players[v].ready(function(){var myplayer=this,userVideo=!myplayer.el_.hasAttribute("muted");if(userVideo)myplayer.on("start",function(){if(!myplayer.video_start){myplayer.video_50_percent=false;myplayer.video_80_percent=false;dell_marketing_util.createElement(srcUrl,elem)}})});else window.addEventListener("hve",function _handler(e){if(e.detail.type==="brightcove"){Marketing.UDO.hve_bc_start(srcUrl,
elem);window.removeEventListener("hve",_handler)}})};Marketing.UDO.hve_bc_50=function(srcUrl,elem){window.addEventListener("brightcove50",function(e){dell_marketing_util.createElement(srcUrl,elem)})};Marketing.UDO.hve_bc_80=function(srcUrl,elem){window.addEventListener("brightcove80",function(e){dell_marketing_util.createElement(srcUrl,elem)})};Marketing.UDO.hve_bc_end=function(srcUrl,elem){if(typeof videojs!=="undefined"&&videojs.players)for(var v in videojs.players)videojs.players[v].ready(function(){var myplayer=
this,userVideo=!myplayer.el_.hasAttribute("muted");if(userVideo)myplayer.on("ended",function(){dell_marketing_util.createElement(srcUrl,elem);myplayer.video_start=false})});else window.addEventListener("hve",function _handler(e){if(e.detail.type==="brightcove"){Marketing.UDO.hve_bc_end(srcUrl,elem);window.removeEventListener("hve",_handler)}})};Marketing.UDO.hve_bcove=function(srcUrl,elem){var elem=elem||"img";Marketing.UDO.hve_bc_start(srcUrl,elem);Marketing.UDO.hve_bc_50(srcUrl,elem);Marketing.UDO.hve_bc_80(srcUrl,
elem);Marketing.UDO.hve_bc_end(srcUrl,elem)};Marketing.UDO.hve_podcast_listen=function(srcUrl,elem){var elem=elem||"img";window.addEventListener("hve",function(e){if(e.detail.type==="podcast_listen")dell_marketing_util.createElement(srcUrl,elem)})};Marketing.UDO.hve_podcast_subscribe=function(srcUrl,elem){var elem=elem||"img";window.addEventListener("hve",function(e){if(e.detail.type==="podcast_subscribe")dell_marketing_util.createElement(srcUrl,elem)})};Marketing.UDO.hve_rfq_submit=function(srcUrl,
elem){var elem=elem||"img";window.addEventListener("hve",function(e){if(e.detail.type==="rfq_submit")dell_marketing_util.createElement(srcUrl,elem)})};Marketing.UDO.hve_ion_submit=function(srcUrl,elem){var elem=elem||"img";if(/liveball.*completed/gi.test(dell_marketing_util.getscMap("pagename")))dell_marketing_util.createElement(srcUrl,elem)};Marketing.UDO.hve_gated_submit=function(srcUrl,elem){var elem=elem||"img";window.addEventListener("hve",function(e){if(e.detail.type==="gated_submit")dell_marketing_util.createElement(srcUrl,
elem)})};Marketing.UDO.hve_podcasts=function(srcUrl,elem){Marketing.UDO.hve_podcast_listen(srcUrl,elem)};Marketing.UDO.hve_social=function(srcUrl,elem){var elem=elem||"img";window.addEventListener("hve",function(e){if(e.detail.type==="share")dell_marketing_util.createElement(srcUrl,elem)})};var custom_marketing_event=function(eventName){var event;if(document.createEvent){event=document.createEvent("Event");event.initEvent(eventName,true,true);event.eventName=eventName;window.dispatchEvent(event)}};
Marketing.UDO.bc_timer=function(){if(typeof videojs!=="undefined"&&videojs.players)for(v in videojs.players)videojs.players[v].ready(function(){var myplayer=this,userVideo=!myplayer.el_.hasAttribute("muted");if(userVideo){var checkPlayTime=function(){if(myplayer.currentTime()==0)myplayer.video_start=false;else{if(!myplayer.video_start)myplayer.trigger("start");myplayer.video_start=myplayer.hasStarted_}var duration=myplayer.duration();var percentRemaining=Math.ceil(myplayer.remainingTime()*100/duration);
if(percentRemaining<50&&!myplayer.video_50_percent){myplayer.video_50_percent=true;dell_marketing_util.custom_marketing_event("brightcove50")}else if(percentRemaining<20&&!myplayer.video_80_percent){myplayer.video_80_percent=true;dell_marketing_util.custom_marketing_event("brightcove80")}};myplayer.off("timeupdate",function(){checkPlayTime()});myplayer.on("timeupdate",function(){checkPlayTime()})}});else window.addEventListener("hve",function _handler(e){if(e.detail.type==="brightcove"){Marketing.UDO.bc_timer();
window.removeEventListener("hve",_handler)}})};Marketing.UDO.bc_timer()}catch(e){dell_marketing_util.debug(e)}},3496429,[3310052],610323,[610310]);Marketing.getServerComponent(Marketing.getExtraParams ? Marketing.getExtraParams() : undefined);}})();